"""生成 tools_catalog.json —— 当前所有 active 工具的机器可读目录。

目录从 BaseTool registry **自动派生**（单一事实来源在各工具类属性），不要手改
JSON。加/改工具后跑一次刷新：

    python -m audit_agentic.environment.tools.gen_tools_catalog

输出：audit_agentic/environment/tools/tools_catalog.json
"""

from __future__ import annotations

import json
from pathlib import Path

from . import _TOOL_INSTANCES

_OUT = Path(__file__).resolve().parent / "tools_catalog.json"


def build_catalog() -> dict:
    return {
        "_note": "AUTO-GENERATED by gen_tools_catalog.py — 勿手改。加/改工具后重跑刷新。",
        "count": len(_TOOL_INSTANCES),
        "tools": [t.catalog_entry() for t in _TOOL_INSTANCES],
    }


def main() -> None:
    catalog = build_catalog()
    _OUT.write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"[done] wrote {catalog['count']} tools → {_OUT}")


if __name__ == "__main__":
    main()
